---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nfs-pvc.yaml
#  - ./ocirepository.yaml
#  - ./helmrelease.yaml
  - ./deploy.yaml
#  - ./udp-gateway.yaml
  - ./udproute.yaml
  - ./httproute.yaml
