---
# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.9.1.12
            - name: NFS_PATH
              value: /volume2/homedirect
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.9.1.12
            path: /volume2/homedirect