apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iWiU2HQkgB+YP+3se+6wJYAesyanPPUATotkBEk2jOw/+h/bRYSuDg==,iv:KtQmPl7x+2zbZoaZaUDex2SqWVFUgSulF8Copwr8Qf8=,tag:UunzLCgSHxsVNYhbgFAbyg==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SzR5RlF3VEdKTzk2QThN
        Q0pvTVJhcnVsNFcwS2Z2NXVoWVorRE5KWG13CnBlZ3BQNEZWNHBqbUVsTFAvL3My
        N0NXQ09VQmNKUUE2dHJXMFNWZHl2V0UKLS0tIDNnUTB4NW0yNmxaTFVlY3pFMnRI
        Z3ovN1FWT3NieWNON3FiWXpuZkhIM28KtqrWvf2urrXP5c7PiGSgwjohcRy9sgc+
        mYxC1tEe3dDEE+2zxIiKk4sSQRsD+I20tnEQXhutpMLT8woGz8WPyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T17:59:27Z"
  mac: ENC[AES256_GCM,data:gbwlnZ8d2XTVL8QwhhLtMwLgwXim2zphCL2Wx49mAMSHMiLKU8H96CFrGabvPkjemFh/rsfMoF3TkQp7W4geJG/uEPV7hxEeUTkUpzQzIhQM1lCx4qLCCnJUemOt2l7D0H+Jk83WuIZR1KQN0W+XSevXTsdsEnCWb7YEAurhXq0=,iv:+rLjYh0g3uwwraV7nA8CAgtkSCVpwa5yW/ktGoJnzPU=,tag:PMvNcuTpH1JYJoomaqXdEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
