apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:G/L3uK4V0s+tjxHygtYlWxinObsm2f/ttekqjbf1u+NAbU5LwS7WBQ==,iv:Rof3tCC2fAcLy5yn8w/9lP59ej6xyqlHxrrY8Eixkl0=,tag:+1X+CLbicW8y7Qg9OmWcSQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQW9PMHNhZWxwY0hPL2hV
        T0xJRWF2Y0RJL1E2VCtsTXQrT3ZERkhsV0dZCmQ2OWxtWkR2S1dDUGpRbmhsT2Jo
        N2hUeVAzU0lDU00wa1p0S09uTU5FMG8KLS0tIHVySWs3OWZGWWFiMmZQa1hkUkdD
        TG9NdDBVbHBla0FNcjBXYlU5ZG5aSDQKjW7eA3OEmfqY6Pb6vklc+A2eXx/ROJwa
        e/KXhERRLoY1RAv/NyQCImEjXn9KNYkpMDLHjX22cRLeSvVKPu3c7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:12:27Z"
  mac: ENC[AES256_GCM,data:1Vv8vLMI52LPyrg9Konbxo54eFe5148Qzk7c/Hc7y3xrap4Tq9g9lqr87D51HmtiEG6dwK/WMOac+a43bQMnjl09kaAtoDyU0Aj9NA+HLQMbjzh/1VO7w2OvhQlyN2qLi6amynfzjlzjbV2Cbr/IrSfP3uYMiCnIfFDWYNEV4ng=,iv:5cGjql2rMLexhs8BHMoR3Kd75rBz+7N6i8c8qmbZqQI=,tag:9qqROw+smA9dXshEkZdX7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
