apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eJCHfSMsLYOFkKgwNlP6ZWBlZQICAFvjCWlUOTsEcaMQop4aHFxGJA==,iv:43673yN+/dGt2XkrHZ5RHy5FSF5wQQtqY81Qu4/gwGE=,tag:kHsK64qO49duM6lEjxGHxw==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTnNRS1dVeTM4elU2MzI4
        aVNNbW5xNVhVeFpMZmZpbitlK0dHUVVaUFZ3CmxxODlBMmV4MnNCUDhvQU9nYUla
        Z0psbUYwbnZnS29BRkNuT0RUcEZabk0KLS0tICtDWE9ma1ArdEVYZ01TMit1UWZT
        b1FqMFVQUWYrNFp6emNyc2pRWWwrR28K9D0wN861oHexOWASjXOLvUVjT2bHG7SI
        J5TwliVGWahXegxpgmhQ2XXwLVIihVP7dcE56ziAu6UUfJmlWFDNdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:28:17Z"
  mac: ENC[AES256_GCM,data:0QQNTKwvv0tOxQemSDPe2gaYyKkEh+w9JRpU/NN9trsS2z8KaEv7uPuPcyuDnsuAc71dd5EFm4ur4Uhw2BsUFsQUw3rS4hTDz85dX4F3ht6IIYiSOPyttIK2GCf/8siy03TRaLN1cNYftTGLRzPo7onqffFF6jeYku82fMy9y1w=,iv:w9ZRqB53v/kF1BQrEu3D0i5UvnkXL5VWzlLmE41HdB0=,tag:aDs89OG79ZpAXXxis2ps5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
