apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:x7Djo69O4EMxJUUMIX1+tx2kLQwaWsXLb4N3EQUHDhNL3Ruc7L5AXA==,iv:lUNj5uQMo8RGgyar0tF8LtKPf//jbT4sOlQ+VpgIqxQ=,tag:2jpFNknENVo4vkgAVuYrSA==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WGlxRkxoNExrM0hTTHNz
        eUFtRHpicGJNdDBRcGt2T0x3Sy9QM1gzaXpBCnJVZFgwTmRwOFVsUEN6KzViNjF2
        MW9uNjFlUmNvenhYR2NKNTA4WFRONlkKLS0tIHhwSGZFaTFUcVJnNStIdnpiR0pi
        L0ZCS3VoNU95TFpkOWFqMlJXVGZsakkKmW5mVvTltZTqQh1sK5hoeqhkY+KYTf+l
        x7DMGY6rbPW0aQYcWJFt4Jv44WNZfubWx1EPpKRKPnVAQJxfj2ApSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:03:38Z"
  mac: ENC[AES256_GCM,data:gMKxrPNP6lE/sQwA3XxKdkLtUZuVeO84L9N/1fYtp4ArzTCKnOYQ7hrSJ8fqEXyaS0T0YaHLasL1uk7H9GUJvGsTlklmOKsmJZscfmGYHG4Iicjgy00FYG0AYXWunBfgHd00M5b0ocxcJ+DXehrni92yFd1kcAUhdtjZfz/cYf8=,iv:5r24mEb8r4PGfbfLv8v/WNXMxPiSC8buaP+gkBXJrlQ=,tag:ANzwsXMdc4gipPbzKFyWmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
