apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:AT07l6i2CpxzNgXSnwFZzy7PuKFocUVjB7wFxBSBZOxceawgss9YKA==,iv:Um0+hrDje9RvS3fEaQVYCNlsEZ5wcFGKqX7QUmVGNac=,tag:BfOGCSgVCIsDUOUTQlkZ9A==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWCtpcVRDOFUvSGlZSHlH
        d29XYjdkc0U0a01vY2dpNDZsZWc4Uk5oaUFZCi9tZVlESEo5TUxtU2w4SHR2TFUy
        RGxGZUhLcnZOTlB1VzRMQ2lhZ0F0RG8KLS0tIDdReTBtNWkxM1hCdCtDWVQwV2R0
        KzZPcXRoOGlJQld6eTM2L1p5WGN0UkkKbXQP6zugvaHZgM8Lo7xGBJbavrCiLDqM
        tzrFJhgXpWBGx9xHtK2Dtkab1owJIkrQOgsrB/VWEx+azSxCJ1/NSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:41:07Z"
  mac: ENC[AES256_GCM,data:xhNrpi3K1awwrv4AFI+gdg7/m4Yp+bhg2fiOjCZEA+r+gjdJhYu9s7NvsQTLBjPQMG9DRJSEPH2VnKqgtMjBBEHaOrViitfSifGS3OYFcdYQI6Cpn5D3S44Ww0ZwDn5VhbDuSuiIhkEX0Rl/KCjDbQm3dHYI4VqTLkt7L+FSdW8=,iv:oXiNtR+gupX4pMtsZRwx3+QkVefrD4ZlOpIgRrbPdX4=,tag:eka+s7yacwlsxHLOv61TZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
