apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RyP0qGYnJcFfnzMIISB6cIoqde05xa6KDOiMVlDIAWWOusMUGlxfdg==,iv:OUa2dzGENCE7D931W13JzePxkKnN35grBk6KxQtqZI8=,tag:8kUzUsNkdnecOwH5B5FqqA==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOWpwdENlMkUvN0QvMS96
        eEVkVXpIdU4rWFNDYlRMM0RaWVREeklkQ0M0Cnllcnl6Zk1ET2s1d2VLS0l4WXdP
        emRuZFNQOTJjdHYxWkowekJQdTNqcVUKLS0tIFF6Q3JRN2xqbUdPWnVya3huMWNk
        RjlxOCtRRk1rTk04bnlKN1FyMGYzT28KSdb589/KAoIWxlH9jhs6tXAZv0cHs0wO
        KW620kZD0sJrg9sXEQRX00brpWt8o7koHqkYefgHGEd/jEfp70561g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:55:48Z"
  mac: ENC[AES256_GCM,data:jXqCDdnsisFpuKQdHD44nt8rhYpFTqqJ0qsJSwnDHzBenry+OFzyQrhw1oMZvemxjc2XdIhvAFMlIxFBylg3ZADaD+Kgo4CYbr03vz/w3fBOEtaKZJZUL3HUCYeilm9JbaeaA4Beky1TTyoqJq5Z8Hy3oju7MO9Ne9Xo1TxBeYA=,iv:k+AbhLwE7TK5cYSLxorWlcxZdt9muRbbyAPOqs5OqBA=,tag:dpN0lSPnewAFzOGDK/n5CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
