apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ijC3VNALSSjH9ARNBbml6lFNR7qwoyxmAuQkrsLnaUu3eYm65L0A/A==,iv:NGbdIK8ZhBJr0WSNwq4R1Srayn/I7Dh9cQ+4BY4V6hM=,tag:v54QZvPC3aUBuMUdpiA44Q==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc0Y2a0RwMk9GR2xxajlH
        K1lsbzc4dTFnbWwzalVwRVZIKytWRUtlUWhVCjZOZjJ2Ujh1bmViVFMvR1FUWTNP
        eVdJTmQ2c0xhSUpDcnAwNzdRZzBiTzgKLS0tIDlZS1pVamlORW4vVWlzWlBUbUEv
        cWhac1pZcmYwTTlDUE1jWXY3VUdZZm8KN6fEvSZ88NXuxf3zPqulytF4oXCOOS6Q
        hgBwnxBIdV5Jib75re6FIjMR46RVaxh7fFt7Fp1xiIbcGXx3fHaFpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:12:56Z"
  mac: ENC[AES256_GCM,data:DHWYGJ6wl1beKwEs6rSh7amUCV8AAEzlsYuAccxQ/0dADdYgDJo2Bmb3418Mn5PTdUtwN+HmYSIW5lVYi/unkqQfnzYpKCZEAPa0r024yWSZ8AcKFUyocD59RE6qOEeJsPPStPeIDY9R8Z4qbu0jj0gs4wYUEib857WRMjGgt+Q=,iv:fIaFBgNPFcArz4vngX3LOrFoiqnJaKrvN6CDS5NrBqw=,tag:DSLO0qMIFAosjy1l4D5pSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
