apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:wAf6/+/pZ/fIDZgbOKlUImV8cvFBWM3IC3CMJdQTJO09TYeBJ4135w==,iv:TqdfQ8lU3y8Hq5HSMOiARh7BCrhmzjIwRF7KVGFPn60=,tag:V/3mTUw1xorvyq61J/UnUw==,type:str]
sops:
  age:
    - recipient: age18wgrx33au72vgf5864ergvs6djplyepnm9zvan83tf52ykrqc53scp2dn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY09iN1A4N1ZrdHVOMUtr
        WXN3dGx1dUZWK0tXR3dnWlgrSm51bFRKSlNRCi9qbGtnZkFJcnd2NnJ5LzBVMExR
        RWExdmJ4dHhaZXdzR2xtUGQvaVJLMG8KLS0tIEhTRmJ4aWpOTWQ1WEp4OUl2SUp4
        cXc1UHM1TzFHL3F3Zzd3TFIyRUZjaHcKgmuGt6Ik9/OFyo+S5tN2YKlBThZMHBbf
        jTsn7x6lo3Q3S9jo8rS2DawFOQ0LHGWo3D93uJIwVZMt+d2+ggSZ4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T11:52:28Z"
  mac: ENC[AES256_GCM,data:8P8NoxkIdFzEddenKoWrI/TLxBZqJaIyfwgLGw47AmwkRsdW02efGiHHCGNp5/hdAVXHpgaVXEuotxqfCzwGozBDVxdIjNfpkFe4cTYGQ8aIQ+Z9ld413no69ugDDEmsfbsqOm9ZeaMA42U5bI6pQl9Hx+gUItNaFbwBZBF9v3k=,iv:0AxWZcqWhEwsHPwv7OA83dNTA+b9kyuKGoIqPGGZYmM=,tag:52n40NbnzzpOI34G20MIbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
