apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:2BF8Dckg/FeJbjrbFnq4wUH/0TQ8NMDJF1PK/5zaonkoxpcWpuax8w==,iv:qZj/7/+rVaLHzbg8k5i95ZKBLbaeKqdvYn/JnWoK098=,tag:Feu5LTI/aWP4GBqTsl1+dQ==,type:str]
sops:
  age:
    - recipient: age1e0q6ugdp3pgka4tq7udj6f9rhxyhtrcvvauqj2mnxhtu3k60y4usraaqah
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSjhsQkUwWGVvcWErMndW
        Nkt6L2puMi9wSXJ2Zk81MGFaWUEzWnI0VkdRClU5dFpnVG1IUXdZbWZDYWd2NWF0
        WUhsNzNpTXNCcjJVRjlXa2VnZjFWOFkKLS0tIGpDdUhvRHkrRVRCNUV0ZWNwSnFy
        M3UyL0FOWUUzN01xSXE2RXpNb0ZBWUEKo9nHBR0/EuBCECkRQ5HttcrVh8Rkbm+k
        PF+y1wsFxUom8cx5p2eU68IDbmhdsyM5oDYxPL5ryjgfN3WOXqeIxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:30:30Z"
  mac: ENC[AES256_GCM,data:mk124NEy3rdy5gC2Gjak8PTbzvjj7WBPzazfCBuoTOsDopyJ5oT+S7GIQPlUsQ/2NdbEH+n8tyOl7+KdJenuN0riyLvaBC1r0v8EM3rMUtwyOyWpm6+tarIqObNiUVXazzV03RXQOvds50B48fAgB+LKhdOQ5vV6gNSUb+5JyQ8=,iv:X+NHwW4vWDZEe7w8D0RbfQoaKZRsCLXLPdga9l610HY=,tag:kHrvAU5fnkn0kFFzqFzHyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
