apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZRQlAl7XVzGmL7FwZwzGWkF8XEm7A2H5AOjZ5gxTcKmu4A18nX2yAA==,iv:ce3C1g5mET2CVWV+gb15xsWriVUi86ARtQ+/s/GrhSw=,tag:bwfM7AqN0t/g02fvIaoVxg==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdFpQUnNrL1NGTENsa2ts
        c2MxSVBFRzEyVUtmWnlQd1loSy9iOHVPT2g4CkNyUHNNcmI1SVRrcTZaTTNiMmxZ
        L0g2cnZNTFpBT0xrRE1aMG9PM2ZHU3MKLS0tIE4xVFh6dzJOY0hRdnJUYXoxZGpY
        RExqUlphdWo1cVRqQytDbHJpdGJYaWMKVTCp/jGlSPGV+02JeBqopF8MuGDnfm1D
        HCr5T8OLybAa+ToMKNK9Pnu06Fz9WHy1SpKD5Pv1qcDP6dUff/KjVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:07:32Z"
  mac: ENC[AES256_GCM,data:5vuXoRVcY8Extj3LmDtBnjlSSdIkCUWL2XxjHkwOWVyPZtKlocVMpFAcTNfyO+2dKutQGQfcGjHteTfqCp6+qxQ4vWQLlXEn1+vkmNUphlwASzmR+BonN3SgnJEeOD5fSPc+Tn8UAamgVNIcFj8S4td0vP0hcZ9UHCs3WNuBO6g=,iv:vrxTmnHCnhtcmDrtzWuf3ypfb0z2i8Ead/8ShgDt3So=,tag:c7JfKVqbrHlcOa5gNKC6BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
