apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:lYLssx3SWvUhttI=,iv:EJ0t0kKWQiiuNIQOPGKwKc+OGG/kpWG6dhGem/jKrx0=,tag:sfRp7m0xqej+mMhta3C9AQ==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S0dCeDMxSjkrblFqQytv
        dmQ1R0Y2Zk5tVTRrMVdhQmwxdVVoSHlJTGlBCjNUTXVPQVFVLzdhNU5tWGxDUFBP
        SGo5MW85N3lwTnRlcmErRFRVdExZelkKLS0tIENJazRYcDVHUS9naFZDVzJMT3l4
        aW9oYVZYeHNHMjBaUWE5MVRDS3F3RHMK3+hmzjeZ7ut/xfzaIsGTgF1idT885Mvp
        7K32SksDyhdPZsUPfMy4GkZ/KM4DcCGgXs1dwzUtv0TbideEV7iwyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:55:47Z"
  mac: ENC[AES256_GCM,data:rukaagohQUGK6bMLhvVQLcnygj4QNvjGxIgay+804VynhebXHEcRWZrLw/rHrh8F+ME9wsLqTd5LqFVwEsvPU4H9E/RBtSYzhIuCxtnwXOVp849q0uwlUTi74SSjKySiaWLE8fFYt+vTc/BlEMmf6VXJJaHHqzR9PT2wbZ0HwJQ=,iv:iK7UbqW4WP8UjdWq1iXRZtq4LQx0uqnk6PkTj+WOOAI=,tag:f+yDNUWVfRm6Kp/YTqUwTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
