apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:uwPOvfLR6GJl/EY=,iv:n4wtYZSvHjw1aykOvl3hrdz9dR5tK9zc5OtqzCJHUqM=,tag:Tc1w7aBWgW/5gM+3RMNzGA==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYlpJYXFpak9PUElZcWtK
        eFJrcThHMnczNVN4UWNXSXJWSTJCQ3JPQmtBCnF3M2RzUFlWM3JOcCtxYzVsV0Ez
        SCtYWm0xQ3R2YUF3V0lsM3RnTENja2cKLS0tIEZSZGVGdjRxMVFmRXRLb1VXSjNq
        VFI4Ymp4RUNsUlhQRExKblNVa3cybUUKg09ealR5AhQG302KeHZW4OatqrgzFJt4
        7qjMcvwTe/pYJ/UYLsMVdC+4jBj1SKpxSebwbubGDVG6D9I1XXN6CA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T17:59:27Z"
  mac: ENC[AES256_GCM,data:xVrwrQO1WXqRfRZP1LivhFuJnknfQLv30HqHhoFPPxPN8XmdC8g22rLBMg99kLjzeJLGv7gvJSdaDyjJShxdcwdsZU56H5bOmnr9LwSo8eCJU/xmwddL/OEk0a+oeXVsOURQAUMLJn+NJETjHuZ5a9sUP+Teuhi89qXDJ0mm4fs=,iv:FcztHKBa6d1TPI//N+qBXva866QHKw/CSwRZWPyj6O0=,tag:QG14fUs1YI9DXHDnfSYg1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
