apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:iJabWeVn4hK2p9I=,iv:/bZx12yu7rQX2ZntuwKydHEjbkBYC03hWHpoNtkb5Vk=,tag:xa6T/rIoycN234W6p17XKw==,type:str]
sops:
  age:
    - recipient: age18wgrx33au72vgf5864ergvs6djplyepnm9zvan83tf52ykrqc53scp2dn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTUxFNVRWRGlrZ3BLU0Jq
        V3dTa24xMmEwM3BMZVRSd3d2ZHR1VGFCeVNnCmx6dVphWFo3NEs2QXVBR0tTZS9D
        VXh5dXplZWdnRHVNVVNoVnpUZVRZbFUKLS0tIG1xeUVxWGdFVzJOcUs0cWsyekxr
        bWF0dzVRU2dRUE1vZDdydmhEdG1kQlkKcpky6RII5gr+UwQ1BkBYQmRUl4ptcNWi
        DCMnufaQQKIbB+P98V+PQFXunzh+eFV2DRjwt+wfvXZ5DoHN6g66JQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T11:52:28Z"
  mac: ENC[AES256_GCM,data:TGT2Ur+4eJQi2l32nQjvlPL9nNwQq4TAPUta0mUHlif4sf8V3a/0ffUFccuSBf1WzUrveKXueijCI7iSjB97sZOuD65TfZqhMRVr8uPtsoG6pdKmtHdVu73uz15rQnLbnDWIeaF7oCskbi45lkp4YOPvyrNH3DWAGEjzh6t1aO0=,iv:hmEJYThaZX5caeRVK06Bjpwo8VDfNTgNdXl/1EPgHPc=,tag:21dJ9ich8ZJoIcLtsEYRsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
