apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HPxzQiJZ252WcRo=,iv:XCE/33qLyCjrHGKYdUJdPb+uihriAqSLVJDgl5DAzDo=,tag:/Admjvp4gZv+IdPsmejSKQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbVAzVngwakVCTXNJbmln
        RTNzYWhPY2hTZHpycnZJV2pPTUd4NEZTM0hjCnRoSXFRbWVCU3JjdDRBd0ZvWVJm
        S0FzL1F3cnRjRXNERWd6ZWh1M2tEY2MKLS0tIFM5YUpLS2NRL0tFNU0vd0wrMDdH
        WHV5YlZCVDlVN3JJQ2xYVnRMUEJNUDAK3OQwPQLrQj8y50g0VxJS3XAA/0G8rj04
        wZ5DLKHUgOgN4Go5VxHaYQuTSHV1RR39bFrMVKQzrAs0VVOZ9WMqGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:12:27Z"
  mac: ENC[AES256_GCM,data:dyh5Q7iVf3cfKz7qNR6CM+eEIPOsw4aTQ5xOdRB8tK+5nvC52uPngJsthJnFx/NSpT4HOE23Osz7evb+Oq5RkFAPYuo+i5YyaYA47ICgarC2hp0DwLbyFRlyr/kmZCEeuZQ/wSM3AWd1JB63Jg5hngza00fM5yGS9AoiSnZsF8c=,iv:JJdsXXpFJU1gK7/h0lhTsLa4lgW7Hzeo1ODI9m2tmuU=,tag:dHWuMJNdFTorZ0CaeHtwJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
