apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:hO265CKcYouViVA=,iv:Ogzdtvn+YmBrs+QIETL472jBYRZLrlNrdSzQ9aoz9bU=,tag:52qk+2cbRfvXFkxmQ6W/lQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ0tTMlZuY0tyK2hHYkNB
        ckhqMFVTWDRPejRkenNHMmRQTnpmWDNYbDJBCnRvbTJIRGJkTlhveVBQc0lIeW5U
        WEpWMC9TOFZlSWFRdGF4b0p1Q1BhY00KLS0tIEdrY3lHSkI1dWp3Zjk5azRYa3l4
        cThWaXRCOVZzSHhHQkwzN0lvY003YTQKOIWRUy2LJ2s9Ws268swy0StTOqgqvd3q
        pyE2lZ9oIv4iBRNRVc6/LY2E2hfNpO+5HywCUXGRghS7KhUrgArB5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:28:17Z"
  mac: ENC[AES256_GCM,data:G2DsSQks+S43lKeoTIoX32hMcjqG1i/ETDb3ln/1SvMspvMNEaAsr8USg6vRL6NU8dnfdPdI82BShkL2z5qyQfeUph0fKzyvj2MWloDuRyO0oTCNTv3+2OwIYlv+oZVtoRw+4MVmpo0qvXi9JW6uQS5JwhyBJO7HV0+kKMCEbaI=,iv:KeUeze8Qh1viqnmHkRIAR5cdsOXttOTpkVhS1041Bu0=,tag:7lq/v4axyqtV1JCowHHVew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
