apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xpARnEIGcaquLxU=,iv:cyx04zWOt868gjst6LiU+yjaRxgZxgttzVYDYoWuCGo=,tag:ZL6xUdBROzfe7lPLxuxOWA==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWnpTako5RVY5WkJaOTBt
        RDMwNUd1bWtub3ZsUEtxTDBneFY5Y0JocDJFClVZN2FtWlVYNUgyODY4bmphaFJl
        VmhNNFNTZStVa1hCZGEwcFhFUm1sQ2cKLS0tIEd4WjZOSUQveHIvNWtWZGk2MVU1
        ZDVyK3JLMVRKcWpPcmREMWZxN0NJRVEKO0KZmEExY69TkwNqYbyTIfVMs/V6Zwy4
        M0Az+BGBSE3h1at+ddY2KkuHZUDs4l2QBPIDzg+v095Yg+2YSm0AKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:03:38Z"
  mac: ENC[AES256_GCM,data:PINMqGawC9u6W/xRHSxXIbaP01N1LGafb0yJRMuLrmfqnLwYh28X+oST06pas12T52w7mryvtZN7tUKw6XMCH12CBeZNcfS7tDZzn2uDQDbMD++II6p2xbfu0Y71zLQqIu2Od1xsCdI0ghX+QOJ/7dPab/LiAB7yGKI8XhvYsnc=,iv:ijMOhwDiBAdimJlnFjCQYdYoO7YYHAMn1Tpp/WwRg/c=,tag:eyUzUAbou3HZmPVg4SYbnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
