apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:7SmymgYl5meIpQw=,iv:Z5BdqeLlVcwA+MveCqpVjXliWbasWmhTBnJ6CPX8yCw=,tag:b8dy85DvC9NpYr7aGaH8vA==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjB1ZTF3RXZ0amF6U2ha
        dVVLUThNWEYvR05wMmt1NWJHYzdjeE5LdHhzCkZPd0RjSUpRN2diZTQyZWlKcmdx
        Y2srUXR6N3lvaGs3QkFNaHh5VTAyVEUKLS0tIHV0WjBUd1BxUmxjY1hVYW1pZm5U
        RUhwdGFpMTJwR1Z1aXlPUkFSbUhYT1EKjqy4xzDCaSZS+aDEHBP9F3+fMDcxnYnr
        ePu32k/k6RZUAwjPtYijui5o04FDgD4AgWPuLMcSXYStxJw4tZSzQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:41:06Z"
  mac: ENC[AES256_GCM,data:sTFYT2fFEPmk3MDQAhWdnYz+GdJWaLDCWdD6BxmKKgfdn9EQW8KII1ZZEOGt2kYReFX0SErDAD8MyMBJlIxrxO6YSWHO9Yz524ea/jz/WGxRU4xKbUR3ZWHguRiWrweYI7JErA6NTDektj6dCDCOc2Y+u7321Yryzsb16UfnWn0=,iv:Lk3dSnVvUSUdqUx0cO1XGGRY1At3tLXMpU95T9dnAFY=,tag:RzCzwJ7Dz6WNvHYxjgJaPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
