apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:A2wo2QVji495Gls=,iv:tnjGI3xk3YUmD+Q0+8fGfQiNn+tnbhExSY2ystxDY2s=,tag:Ra2qS8chpLVM1MthwX6uJQ==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5K295UXZSeEhFV2dDZHh2
        dEkzQU1vZU4wR0JKOTZKMThzZGdOWGNBem1RCndYMHdaQWV4UGJ6ZUZTUEl2a2pH
        a2JTZVBhZ3E2V0l5ZlMzaVJEMjFvd0EKLS0tIFpqRnUrWGxoanlHbytPTEIwajNa
        R1pjTFppTGsxSGtiVStjbkVRZnR4R0kKteHErG/p/PHXbVzQeEoVacbk5yOvpUB4
        /g+8d2n4oy+Yl0KZuYgkMOqtcUvVTPuVGGrVeii6qO/9FnhGs0oLkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:12:56Z"
  mac: ENC[AES256_GCM,data:Nh0r+sFqUo/63LSwwJM5s3t8LmJqyPeEPdphb0D8Hw9vsq3AJ+f0W9nPSU+NeKddw88YN6amJfUjjb7Ftc7SLDHkOEkfC48gsMrgc/GfbVf5xo1U8aA5b7ZSs64TwU9LNa+9x18yhSnyXS4oDZduqOjgAFDyWEgKULmHO1ApuQw=,iv:NOhbWkiLuuuePe0T2/nb1sQI/OkzKvF4gKIDWmDmRns=,tag:wV82WmkymWAnZnk8QYRc3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
