apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Z8JJVJn5xvr/nO8=,iv:Tswk9/fpdtU9RmZQctnXcyNFgqw++RMjT4eYKMzTbMY=,tag:uN/+Zs4o564mCNloNTRpXQ==,type:str]
sops:
  age:
    - recipient: age1e0q6ugdp3pgka4tq7udj6f9rhxyhtrcvvauqj2mnxhtu3k60y4usraaqah
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS2cvWW80VEtTYU0xbnpl
        WllzdjF1ampMUktxV2M1b29uUUxZTGJHbVZnCks3OHBGb1liRWRwNXZnOFlFYW9x
        UnpEYzUyT054cmdsTUp1dTA4bEdrd0kKLS0tIHlpTitRdDRJTjNmNW1OcmVBWmdz
        ZTl4dHpWY1BqRXBDTWovNUVwQUorQ0kKnvi6zh11VJUDiGzcoUARNtjAv+662W2w
        OeYZxC56ATYdBikYAnJ1YPY9GQMN4gCp2m2X0TmDuo+neRL6dBsszg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:30:30Z"
  mac: ENC[AES256_GCM,data:wMOgQzZckpOXBS0fbQTmvnaMNRG9uMNrR6uiizFTGUbgTBfITnDK4yUcgRbpmYfPdqw8nIpx+xS3fM/CBvSg3Mf2oPq/6lUZDG10PlrgAMH58D4SMv9bVlMUJUpXp9/twajD6w21zjO13yeNo0h+5/5uSsaEKWkUkQBvzQP3Ui8=,iv:CclrhMtlZLuetO0Tui5d8zuCZlacXUaUEvTLBQaTAus=,tag:SNWzbUE/+HtDtFZ5vM/9og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
