---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omni

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
#  - ./tcp-gateway.yaml
  - ./omni/ks.yaml

