apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sV6RHeyM22fRspZjC/wOqO5k525Dtnps5JgDe+zVuuc=,iv:S238uUGQJKoIJVaZWcq7tKtRJWgSQX+kgt0zHlnM6B8=,tag:hWO1PGCFuyaxImUT0U1ATg==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaTJ4YXhMSmx0TkE1SG1s
        YmYwZ0IzSXJKRzRYb1VrKzNKaWc2TG51K2lrCkVKQy9JZUg4U3dmK01EdHU4akx4
        cEVQTm1ZK2lsRVNsd3Bsc2hpZDhTbVUKLS0tIG51V0d0OHo1WjlEeWFkSjI2Znpp
        cE5jSEFLSmZjZFg4OGpUZ3JjY0ZCL0UKAUJ6nk2IMijmYUW7Z3kIxYBNVsrN13qP
        ntJHjka7ovvvkXlzq3B1XYu8sMrkBhXjUvN7zuj4oyyXHjw47dTWhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:28:17Z"
  mac: ENC[AES256_GCM,data:gR5eNXXAB2N632b3FuwTGbumfbl95T2b0t+WLahie/awV8MTEogAF2LZA3i++JqW/E/CgS1SLMqbWJmtzjRQAJFulxlMrZ7f7ktUgmU7f/u9VtLXfOklG29Hi/QA/KrrdUqiAPBdlhAB9NwBIKx+6d0Uo71taoA6lYcyalNNpGc=,iv:57d/pVYtVtwBIJ8VgT35pMf8SikoHVSX0+RaClS9CmA=,tag:FjsyXUbjdTEISpCRHHiSEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
