apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:I99PsengPE8jHPRUOt7qU+3eqMnrlaNlXijtzoAaGXs=,iv:C2ERpL8+h1xFWIgR7dz05yU1o+kTH7S0Fy7bJCuSTls=,tag:HmnQubWOJD018nNT+z3Ang==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU0tPNWg1SGlqbkpCTyta
        QXJZL3lkS0dyNHF4L0VhOEdPMktBSEZxWkNrCkJCd3JSODlJOTdqTmYvU1dQVStt
        WUtzVmNML2kyb2Uwb1E1WXlLeTl6WVkKLS0tIEt3ZnhVNUVIbXdFbmd6L0ZqNmtZ
        cmRoL2RJM1dyT2M0WUJHQThhMnF0SXMKpAp6VsGNvjITd/dO94Uoep8xnvmiEFQG
        1/QN5tNfT8onHo9r96K/nGDtRzYuLDenLigrGJXpTD7JYrNO9UaUXg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:12:27Z"
  mac: ENC[AES256_GCM,data:Noave0V2kemG8kaf6KUxZur9NKKC4GSJuZrYwwB/f/xz1oU9nl3xhk8w8+eLM0mQ6lwxDowjsLVCjSfDGZwM/x56YGtBLWur8sdh8+zVebSAXruxKPv15ukVBrrd9FgLlFbPXf/tlOUvfCObqUdFUGRc26PZdItINCHkkyoCpwc=,iv:TlwtPoaMaB6Dm/g6teYaEuEvKKPMrdze9QLluZA1NYw=,tag:9yhq+QKXri7WKfRsdXW4aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
