apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:w8GIJcDp7QGpb2d51QNdfbj6hnRQk60g5bYpkY+lgcg=,iv:ksB1AJ8OSHboZDnyF2AVV4Pt7y4Gzt9A5KGwL6c3Wug=,tag:4pzIbWZyjN6jED1uQ9/2zw==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmxrcVIyc2VueHZjZDY4
        SERlMzhhWW5rSmVlTG1zT1o1dFl1a3JYMUJBCkcyTHZBcTJSckdlS09MMUZOS0s2
        VjJNL2hwb284UmdKUThrTkxZY0JGTUkKLS0tIEo5d0piZ1EvVGM3d2d1Mjd4T2pk
        TXRTSThWN3JKUU05NHpheWRVZzl0VHMKryN+2WAB9XKY4Je30UngZd8MdFwfGER3
        FP1U6WLzfSarkGYAfgM9EufkVCXW4g7w1r6fy65iF4s9m+jnwi4LOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:12:56Z"
  mac: ENC[AES256_GCM,data:MNsHbed4ydIPByZCvYu0ptjsHSMWBQKLW62rBoknRMyjows51RPWfQIb2kUCjAE5amyDrY8zsuJF9CtiAqT34RF5OxWtEFD7pW3+nMMZdbJTRQNfxO4qItCOovC+QWJvEPCmTlFCN0wLtrURberIZ/UkexRfJkNsvM4wLuvGunY=,iv:WkcRMKF/EvE/JMtaPRqhtyvnwoO60xKpxB0PV0dRYC0=,tag:FOjbc/gy3Cu50TPXRzXxSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
