apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:MNVUnzB0391FptCjqAvFIIO0Q7oMhyH38jOdlUZiq8o=,iv:JBDln311wWfY7q4WfA7YYETpzz07zMkdU013ypO/aow=,tag:MhD5WTPr7fsuvvDQHSFgtQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObE94di9xSDRBd1VIVTdu
        K2IzbERKa3NGTWJ4emFrbE40WFNkTitaN2pFCmZKalQzQVp1Wk1jOEhPeUlMdlVa
        eGVaZ1A0cmI1dXVkbDhIMXBEZTZ5TG8KLS0tIGEzVHArdjg0NXB3eHZ3UTY3VGFp
        Y0R2V1l5eEw5eFprbjdnYWZWRVhjQjAK71m51dT8f1jzvLvoGJ2WClc+m8kQEpRM
        PRYZ0fQE3VfBDpm+zhpuJP40Qld+5ZAgMcUMLz4gSL3YjrUKiNxEhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:07:32Z"
  mac: ENC[AES256_GCM,data:FlW8mU7FUngbtLq6qSWfGOwnpuDF94xFUTQyNY1ZOvfF0YCC1t8hOM16UuahGW3yW9TLcSPwVGXh0fQrjVGuOQNTzgZSQJNQ8e7zeI/KPZeAEMqA5FHuXoXWM74Z41bZ0qDup9Vt5V2JUtJ+fa8lbjlZDX+StNemzNZxNbGLQto=,iv:fwIjsJjklaB+b7VPoQxJjMLYVD622MWJiXiFZO8vM4U=,tag:g9T7+6FYQ09hPmGZc9dZJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
