apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:hstRlI8ixTY+E1JlQhoTU202Pyij0bmr0KDX1EzedAI=,iv:Mj6PJ9xKUPJsHvkcvQbXef95XcYv06t1l+G9wUEvs/Q=,tag:9wXGvj7gjpRbHuh26CLnsQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZVIwUkpDZHFhRHZjWGsz
        ZHZPbWYwNVhVdDlqMEthOFg0T3YrV3VVejJ3CjZHZEhzUEdZalA2cEppUWdNUnpu
        eUZoT2JoNmxicE9uVEFFWmJwcm1jN1EKLS0tIC9YYkZDRVdFamJmbnVGT3pjanNF
        QURLTitqWVNGTVV4TDZSNkZSY09LdHMK9LrbCK2jloCuQB4Q3II1BfecQ9VC6ozC
        nbpgtDxeqh4qwfRsoYuNLnF8Qvw2EbNsdGLTsorf+xbmi+J5gUX0ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:41:06Z"
  mac: ENC[AES256_GCM,data:uKB16kwKjCWeOA8kB27gtkhqgrX/1bTru2nUdBzL0MpPW+lHHKHPw8YoQhxtuMkaHeQ25Ddmp3oL8k9wGd2gut36buHH4vhj5H3lxXgWmjf9Xa+hyK3CTcF1j6Nf0KckE+GvJe0YhV9y1bHouIeyC9rujaEGPQaNyfFzHHxZ0cM=,iv:ejpp6yLWALafEpkERJG76oPwlD/eq+dCgTjlo5uw68g=,tag:UkcxPPx9817eGxFqgUQ1/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
