apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PA7W+qAROBrIu/8K/9gUVRprQzBtff93fR2ZRaBJcu8=,iv:gHSMXryKiO7VzvoZWEeTQQBjVHP3E5CFr18uPZm2cNo=,tag:m7+wiyHiasBkuodgrKuipA==,type:str]
sops:
  age:
    - recipient: age1e0q6ugdp3pgka4tq7udj6f9rhxyhtrcvvauqj2mnxhtu3k60y4usraaqah
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodHg2MFZVQXFidnVlenhs
        VkY4dHlOME5EcGFDMmVZZlFLdllIWW5KT0c0CnB4UHp5cWRDVHNWQzJtcWJvV3Na
        ZWpoTEJEOUZuRmZKZkxFb1JKeVhiRkUKLS0tIEZ4NkZra0d5Rjg5ditkYXhCZ0o1
        cW93TFZXRkRvTmYyQ2Z1Y01lOFlOZ3MKCmPNEuGnOVuoJxANyt8C+EuWSyJMS7UJ
        D3XDEtWYP+i+sAdgUZAG3fBmub2NabO0kYrKuHBS1QzGA6pdNC3D8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:30:30Z"
  mac: ENC[AES256_GCM,data:LRNysHSAnADFHbqD6m77N+m403A/xWLnFzp2MssYFKJ6CNQZ1UGtwpCR92/nn+3x7O1Xk+I2wHQyWSKrmbHHJqojSwPQbDaLTeE0wCQofOO9a8aNiieDIV5JH2/oI08PWX2nsNe8vZGAbfjvYnrqPUi07415O+cBeWO9B0aYx2c=,iv:7eNV8O2fzrscDwStec/Ai/nndWEa2hdBGhcD2L9MDgU=,tag:axw5dhRuKxdGaqM88MriLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
