apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fwYCR7msVvEv1j2GL9UR+oxQBaEdgOiXBzs87baB3dc=,iv:TTVQg7asqjRU+CnGsWyBDAeGmN1mx7mHPC8rsfVebfY=,tag:dR4Cq9rm1NwooBYbQGJL2Q==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYytOT0VtczZWdCtnTmxk
        VE9WWFpaZHY0OVZZOTliaTZhaUF2Z0xBb0ZNCnVtMkZrMThKTnJaRDE5NnRvaSta
        TjAreXM4dDE1TjJDdW91MVdRZ1RUQUkKLS0tIERDZ2sydWVkQSs4T2cyTXQvNEJY
        ZVgzd1ROcC92VkVjUmRJRjNldERpNW8K8VJRVjWvxSFKsTJgRoP5MTLNgvOAi5DY
        VaZYc9RnfQ5vIq6o2XWNe+RtOKowDzcggKJ16Hk5zVUWLO03xUn2Dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T17:59:27Z"
  mac: ENC[AES256_GCM,data:wRZ59D4vU/roBorGOfMGZAWr/HPpRQVAo8+JFUnHlG61vtuVBsyoAwOr0VhJiQNAIF+gGY8kQeTB8n3Qe+njP3OTvznIEF9bjt3r7eOHq/bKjK5LGfgz9UM/NU04sltARawzuVZz3nUXrVZcJV9mSbQSZS75qCOw/01CreWVGJI=,iv:i22F8wVL5lKzqDBrfRbghSVoKAnhn7mBMx5cXqI2O0U=,tag:70bsCufI5IJOpBdwLJkUyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
