apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Nj3UGSHxHqXLws+kC7xn1kSp/ANXaytJn2DabDc/7cY=,iv:vl2HmPavqRrHzqIFTGygB6CpSIWuJFKx12Echm+VGwg=,tag:oMYR0/d3/dcwHe5qAmUBWg==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ0ZNd1Z2Sm5LbVRzY3lG
        Z29tR2s3dXJPdTJ2RzZhTk15NFhnbTV6VDJRCmkycHN0QTFtU0svVVdMSHNzalR3
        b3l6bTYvN0dhcXlBWTNZL3pzOHVCQmsKLS0tIGpOZDFTL2NFNDRhM0lDUjIvMXFi
        dWhJRzFxQnMzQyt4Ynl0UW9kRzE2eTAKk0yC6j8prw2YHfJ++UstAo57w5/gxsSj
        t6DaYesydN/NSigLnwIa2cz842ShEU1D96f092Ez5i62R1HFKW9q8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:03:38Z"
  mac: ENC[AES256_GCM,data:vNbV6zViCsG3CrBOtqJjVBB+LpdVL7cayEBgNCeEjbzpbJLnOE5EaCpmc1XUXNZP8azjV7hTdOxFNzmtvfIZX72olNrPjnREw0db2ftOYzn90dStUUQ4aPAYDxJWpuaiodDcxVtyoGAmYxypvZmSLnc70Wm/t9kWhLsJfCIWyck=,iv:2tva+nknt2j3+/9wQvCBiPSxBJ8FFZTOywYCEjzFpE8=,tag:Xe0MZd01cfM/mUUSNhojyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
