apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:D1Oomkl/sMSGD+JGrZNjWi9MNQQR1gZ3dvqSP7Nkdg0=,iv:+9+ODSi/m95yWBJJbN8SbFpbbOPK6V4U1cfYA0gv0/8=,tag:UKzu5EvxVxfxZnxbzAoRqw==,type:str]
sops:
  age:
    - recipient: age18wgrx33au72vgf5864ergvs6djplyepnm9zvan83tf52ykrqc53scp2dn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZWRHeUdEcERMVkJwN01W
        NnViNVdwWkNsaUI4UUtGQngzN1BJL2JPMUE0ClZrakY5ZUtPZlcxUUtVZzNTdVdj
        dlFuWnpoK09OSUZRT2tscmJOOXNBOFUKLS0tIFJmRXFXa3R6Z2V4d1dONnFicVB5
        L2QveGZFT3pBVXV2TG80TEpzRzZqR0EKJhH8chXmGRdJyLEG/td0I05s3p9jshIh
        A+l7QL80hGEZj4uCGa1ajpBlOrCOqGHDEctNtx8d1KqIG0SHpauKhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T11:52:28Z"
  mac: ENC[AES256_GCM,data:r7Q9jsxPmjz68SA//ioU6sKzC76AuMG9IrVtv+AlFHzXcTFCYvYtXcqc0Dganv7pNSnWSFnf5InjlMWVzaclcoRSRKf5m0bGMaO15CZsIUMBRmjdrOGmbfwQX3IvlMLHdG8YUDJayfsIAlUaVCIGFwuntGUn9ix4ZnZfxojSyG0=,iv:jc/IEJG/0+o/V13f0fgw0HptlYM+munWza3/VKLQSlg=,tag:Pm25NL04T1lzg4ugaygkyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
