apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kPKGufFYMYqwydbP0YdnZGYiFwf7cG6c0cbSGB4T1K0=,iv:J15Vvvr/As5dNmGQz+F+Nod0e2WZo38/57ey3w3dl3g=,tag:znzaA/w26FbhrKnJkVIPiw==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOFIvOFg1ZWI2eTZIRjNx
        Y2kvZU0wUEhKVHNsbXhZbmxMMW9wZERDdDIwClBVT1cyeVJ1NUlWRGY5Y1Znc1hP
        eFFFUGxJTWxQZDZVck9pT1ZLOG1SVEUKLS0tIEVxN1d3QVNlcUFiSEM1T0dUTzZQ
        MUJKWjdKM3oySnJCQnd0S1U3aUJpKzAKPmtgl5J0UUIH0soReFvfPPzP2CTpvthY
        23tT0x3qBKIufZdkfKq8nDrIlpNt4hld0TQZBdBJ6fGASYrj82DZCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:55:47Z"
  mac: ENC[AES256_GCM,data:D8W+R93KcsTtssIK1BR+CS2vZj37Uada84tqS+DZGLb1Dg+3ZF5fcioHTQ3xi1XNr56/6lK16JSK81fO/ZYBY5ntTt0rLsB14QkGvwkzwgTxhsFBrejnUZ/jL4MQIYGK3eNVe1ACkGvdidMr1cpg2XJaYCYQLHFJsDzKBuO7nYU=,iv:L+gWfVZ3VwzMsijZB2h8tuCPn4mJhK0QgBrJQzfyaa8=,tag:e37dTS/X7ZpSiuCWb2QIxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
