---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nfs-pvc.yaml
  - ./certificate.yaml
#  - ./ocirepository.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./grpcroute.yaml
#  - ./httproute.yaml
