---
apiVersion: kustomize.config.k8s.io/v1alpha2
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./echo/ks.yaml
  - ./homebridge/ks.yaml
  - ./mqtt/ks.yaml

