apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:C2nym4te/YHttgJ3MJ/9psUMV9ZHGYXmPMVexCXuTo9fKMFDSXXVRbtLBeh7r2vFTM6whN8cChZnQPBFrq6GGzP4v6VNpk4ccSslpcsgzQPc092Ns7jxdd+AtX/AgD5TRlqIdaRT7ydSrySTDSmK2umEtn1sBDmDjWuzs1Q+B0T7oWg9870BXm4eaFJEmYef1xEloWjexkt4+s0jvGWyHS+iPtBRGTCoHtjmgzQZ6GTdd1au,iv:U+CMGwounIsCUp4L0RVPi9VVt6J/dsuaNraDTMx/iyg=,tag:9GuSfJKoTTCpoUIR9dHr1w==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzekVudjBxNjI4UzVGQlJF
        dFM0Q01ISGxuRzAzNUdMam9jMVRLcnJrQmtrCkNJQy9hbnRTWVNZWktXamJvSG5Y
        ZW1WdVhySVVJcUVBNmVNWEZNa2hER0UKLS0tIEVHVHNDOWx1U01ldDVaaU5UNERZ
        MU4reGNSMzlxdW4rU2w3YzdSdW1mMjgKlfauf5ss0CbBNSKQjixHCpwtX9ULS+zi
        AiHF+oJh4VGWLWVhpw4qC6zKkmoZOVAEgAeIGQbJFBbHSct7+PAwWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:07:32Z"
  mac: ENC[AES256_GCM,data:5OeCDLYS+7aZ4Yg2IZCSvMITnNtwfLSm/glyNYlbWNFggMvODuTshyOfFvtiAikYlum5b1Sx7U+I/6jsCaRzK3thUivH/Xdg4u6JEVp1cMows2JIpk036UmpHrfXWA+/FUf9gzPT60cqpimR6b3TLn1W/LDPriZCyEFCDEXmb4E=,iv:pjfkwS4XwhSjOQS6Off+BLE56NgVtQfagHAFnh/a8VU=,tag:G8WoWz1cp/kD9DBAMfLy5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
