apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:p6afR0ULxJJgYUHrN1ZWmNQGP86AoFZOsifetzVqWJ+Qr1Beq+n/yDPYQ475Wh/OhTznZPKk/vR18NnqiQAFC2t6/LV1amBfaZ6kIMtpDu9JjLy0fGz7CiWhR0dsIJVQgEOtlr7nLcMc/A5cbUNTiTnRiG7/2FURI/1aVE3OppkJemF7OdhmTXyaYksDKwEWIagKG1zUC4tLub6W3YSQOxZjPqi6x6NB7Howb918a25Nabte,iv:u0DAXUkJLJlKAcJ8eVsZjBdxRK2UmrkTFmuaIEqgx+o=,tag:uZFJsVS1GUGEYHsOeK+/hQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNnFrMkRFUUZTTjZwWVVh
        dmZxMkJNT2F0U2xyd1RGeWlFVVVBOGd6czNjCjIxVWdHZld3YUFUdHVCWFluRDd5
        SHJYZTB5UHUvbUQrL1R0OTJnMWRtWVUKLS0tIHNZbU1CQlV1T0NxVEEvMkJQSk5D
        bkp0ZjB5aEd2Y0tYenZlY0Y5RXpHUTQK759SKITlMtYKNqtLYTVmW/yaaXMvQby2
        sdaOSLDZzARmHB/IN86OtxHpTtZrnR9dDPHLzfnoE5exww99xpLB/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:03:38Z"
  mac: ENC[AES256_GCM,data:GCpspjbpeUbFbUtQLMcRRI93QecyVG0i7F1PC2b505bzTJSqHimKwHWj7+fHhXMeigupdEf970ls9ZXeF1ZzmCKSySIY+P1oMJXNe4m70uXps4lUCv6oAoo65C+VqwWvOx0VOj9OlcNOZG4XOWfaXFBYORuvFd1rdcQaBSDMk/Q=,iv:ZcJAn+2OjOuB1wA+bqcNATB5tATndz48YftAZoVc1DY=,tag:sZ7DxnaGTRXMPThwy41F2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
