apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:J00LNuHirxJg548pFwgaSe7yGXwJR8Ziz2CqrBCpHqEyVVOURYFK8jDRwZKxqKosivo8vPrccFHG3rM/KjGIZOfKRnPU5J3favPQE29u9rtB5m0qe81YMXOYahiFuQ77G1jkNe1L5iaRJBtuelOmmq+H4HN8Z3oCuB07RjwOJaIWyEOP+ufP6o2882SxytRpCFFZhwvA8U74cMnZ0xhM5tWQZ+IPAcQZxX8ooqNy2JGbc2W3,iv:I2NByfIN2Gi0irhn2VnxlVOdpocPDblgZMRGgfKITbM=,tag:Qwevy42qZzQ1bRDJXXXz2w==,type:str]
sops:
  age:
    - recipient: age18wgrx33au72vgf5864ergvs6djplyepnm9zvan83tf52ykrqc53scp2dn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS2t4N3dnejA3ODNQYVJt
        ZDlJdk5MYWlvaDBRMmw2Q1k1L3B0eTZxVlhnCnBodFRiK3dxNDVTWnI3aWl3Nzgx
        SkQ0NkpFMjlCY014aTBJTmJmK2laOEEKLS0tIGFWb1QrV2dsOHFkcFJEMnVjQVBF
        eHNyVmVUUTRMeDJYNWQvZ1VTYUdhcE0K3aiu4WZrVOdvrxFFie5sq8QNw7vcQAC1
        VeWKBKROXz0BgOLZ7vcWJ8jlJWHToBlWTKAguhyqGAUOwlc89ecSkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T11:52:28Z"
  mac: ENC[AES256_GCM,data:j7/49+IIw45lLHQ0cPvCgCSWdG0fm5vwXZiCr8pBdVVZcr0J2lh8ZAtOlL1vRrVOpLqUztydmDV5uYdfNKan2ZhSOBcJ9no1EDEpB4VwrWEAqcoqmw9m7ec2G+7K1C5GXLQmIH/O1ZFYQsi53Ut0YVhl1/GY4/fgOUQ1mZudwQw=,iv:4nf/Tkg5Kkj3q5CQK7R/WKfK+ZeMWAtIkw+1FVktT6M=,tag:0jlRC9ye1hM9yMcaIEsW3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
