apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:DR4EZPB7hJ0ewG300gn4qxzPkTVkImUVE4c+ntsw3kFRtA/pG0CKsescVHoUuEZskCRtojRPGySdrO6stYjC8jp4DowZrrFsKW5lLlXkxzLTqwg7Xu3MGR6uIDyB7y9afnasE2fUEKbgcpwqlBrI06aRK8MymQCbDr10P1nSFDSw64oG758fQW1kNw08QWLzVu8Qe/tvlQhY+Jows0TDGNsChKZyilHyairzO6J3Aqz9Dnyl,iv:ySE4oslOfGjEj74GrG14B4Y7s80Dc42VXvU63DrX/Fo=,tag:FGK8xWPUX8lKfeJW3ZPxUQ==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzY4TWhBQ1BZekZvUXM4
        SWlOTVAyZTJhTDJqazlyYjVXNzFNZm80bWl3CnZTeFBhOWxqSEdMaEltNkQveWZI
        N2FCRUxTUFZHK29DUUxnelVkNU12U3MKLS0tIFFodVJXUytrWHlBcWdQK3VQRWcv
        MEFCYUROSjE1UnZDeXdnaXdZRFRRY2cKp+hkEDaEvMfbwc+rXGd+OExNaK9PJURd
        BGK9ljrkz4JM2larEnOtAntajE0knOB8mhduVjIRD2vd1R1BM3CV6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:12:27Z"
  mac: ENC[AES256_GCM,data:t+Jnfh/C086Efn3ZT5Euwr9zwVfnZ9ACZA92EmTAX2iTR7w80wiyoQ2RRrGP5tE/GaNNONPC/mE/jN9AJGG04n8dY09rG3CEDBBS1dugmqhS6dOnkK5QPBnmctHXn2X4kX71Ku2roLfD15KNxEY/hi36hjf8povCveNG6TmkUTY=,iv:hIxyclDd95pqBn/n0HDbNVc+LP6AhKYR/T9Osb2ChwA=,tag:415SszMFJA3B3uZMsrynbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
