apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:9advL7q4DjTE2e8ginJRq2XEC/vxXXrM7H/axEBCYFHYTnW3Vp8BIcJBdOqaSee4PNem/S2oG8d7Skc5ExVn6zLlXVv0+wOwZ4PBLiNo6jSqf50hjsHrD+RmRyaX1f2KWBuARMZ99CBsLkDtCMnWY/igM2iwLvnLxEPXnsxhNSRsm2hYgRF4nG/rLf8nzFd1ZStbUNloNGpVt/zjuvn6IYEMwntjnz07O8R9asAEnL9cwGPN,iv:+UiRd5JCMpBnNy2QTjPnPyj3lXocY+Bk3pq/Km0Ih14=,tag:TECYru+2s1v2f+TXQ9GfHA==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRmdyYTF6ZUlwSkw1TTBp
        ZzJNNURvSFMwQXl2RVlndzRtRVhRa0tQOUNnCmNTaEpuY1FHRmk3eG9FTHJDZE9h
        NmpkenVscjNXQWtQTUNnMUsvUDArZXMKLS0tIEpkcTUvMzllanVaR0huV0N6NXpk
        ekI2UzFGZ0lLcUJRN1RRRDJpTWlRQmcKOgkN/rq9trS/TR3ovK30nJ5Lgrwpx8Zh
        xeGi1BYFz6WGp3MZHBpXJtQKzpseb4lz1x1k8MYW6nMbGkDWPUDLug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T17:59:27Z"
  mac: ENC[AES256_GCM,data:M+Ei7SxjkWX+o6Y34uBALgh9yB1AMtCc06ATYoW9Gy/G/+22ciCaLLoptsE/+VYAeF6GcN8hVLD46c2EgVFgNYkSzuG9tg9K5VaMaA4sGyzkLWqseLAs/+8hs9vBVRu7HNwCYJ0/lHFZZlYenwFJET6h02evtD+8dP9oeQI4EQ4=,iv:FBsZNe32fEAcJW6b69UHfNfAewCWJ7E7QQ40UHhptvI=,tag:1fCbMWNsNuL3IqfnnUG6Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
