apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:nUwHEUydYh7WerZe5FsLpJ3IH1oxtz2pzQh9o3ddDrSs9PeWkaBA9GpzFRFyrNdrjhhmUZBDwc0lJHJmXeJ2UfLHGsezHc8//FVDAHmHC+hpfQKAP6daNRrUU5a54Ypwot8GrZPjGx9cp9SIDgJ/SbvBsAlXBbiug/4Yuk8KfIty6U1kaokNSGk44dw52cLYmO1I8+W85X1ZMgGCOSZo39xe7irs8qcgIjNLudsGwKGsWaaA,iv:hCWeMjk9JlYq+qcKBAZgYZ/tqZbvh4vXdBI7l6uJxuI=,tag:vKFjX/KSrWAPikJHTPmLXg==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VjVEamZPd0EzVHNWZURX
        aFpvMGdLLzZXOEhHTDFYUGtSKzZRSlVETHl3CnBVelpuNGdCcWI4VTFEa2IwTWpz
        cm4wNXJMc1pZRnZOVUd2Q3BRc2sySEEKLS0tIExVcGhaeFVzRzBsc1lTazZ6Wk1z
        Q0liOUZPc0NvbzF4NjI2NmRUVGlBdTQK8wqtVrJNasg8RH8USOuI22Wof+GLU4tJ
        es4yFB2u6YwahBG0EpDslucMzkYsG8KnWF1z1mlPxi0L2yIZsuQekQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:41:07Z"
  mac: ENC[AES256_GCM,data:eyhifGmBEnMtbZImJ7xLhOu2QrN+WW4iFfNgjJLfBmYKE9gIHsjUtHifoP1Nm3w++SpLzSCjrcXbMmllqgoWnXdMjyerv81RkAo0ppP+AWS8MzgiVkzOCJFne3frQKt4Fu4UqS4oBA6ba6uD5VX+XtxJ+CPeYZB2k8qVsgEvLA4=,iv:q5vTzx1Z86L1uMDlcHMwfhMQcSXwVtK+/98RixEuZ/Q=,tag:YdFN+gD7oxb17+FTf9EnBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
