apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:pL4IYVLrBI+XtuzLjAh9BR3JXd9Qkhe7ZOU5909GJF386PGm6EVPijFIxpGC0E0GHgVaJVxJZlFCJXx0v0NOaYwEBzyaAN8u9IuETN0sjTpzuaqungJ/X0XZ+hUlv6Fa5w8gweIgvMNVc+L23JLA3MHAGvA7dz/HZsd9NYJ3IrxaSxZ3ts60zTLULlopTOGzpisx/q477PKoozBAvKmCYz6u8RiGskdJv1nEPW8Tmlw+9U9r,iv:KtE2dnEmlKAzLfO1wwcF95+PXpZjUGVgvsg7C0htFP0=,tag:CbYYLXng5BrEJTa0KH+BrA==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L1ZPWnpLOXhHOGFLSUJL
        b1pVRWprd1J1UHJ2ZGpGalU1MXROM1kzZ1hnClhGamt4eXFkSWUrV0NkWWJvU2s4
        ZUFoVERCcVUvVHZzRmUxSlhQYXRjNUEKLS0tIFZHMDdxaFlzOUkxbjdBcGxRcDhk
        dHMvZ3lkRktMN2MxeHVoSXJ1TmF2SzgKTCRFzYKMtOy9ZBWH8x3siDKZEBXTNyc/
        nFqLJcJcNbrwVKcXCEsnWBF8jIW3DluBem/dQPkJ/SumxAV4gemejA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:12:56Z"
  mac: ENC[AES256_GCM,data:peIMnPwqr84wz/5PTMHyRJHUokiqm+/xDkHhcYeqe637xvpzqJ9XyyazzYlLZzgW03bVpo6KlnuZgx5IfBmeOIzINAKre4PBj035mtE7Sbq7co4Px/tZm9+qj39A/eYkmJJuAWo7Hq3YjZFiB8DH5DtcMUpYHaL1NrXR390ae2M=,iv:zipcDE9kEdkTOyxkGxgop8ATG8t/yfWXmfkgtHLjDQc=,tag:I6L5kQnCQGe3taFRT6z2rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
