apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Gx0NZASrSf5FYPq0epE7MbLSYR7mLqxR21UF3MZgZhqGo18NxV33icin6ZCF7rDLjSzFex0pYRx0YRfQpmdxFLjgQb00cAxnLKkXDYKpDMi7Nq3Bl4YVuKg42/8BQWxxqJX8Pj4DSqNaxC21KOLr5pMdZFMniRjTQrCvhpXGCBXMGWUahE/kTof3fObjrJ3CqkhQBMfB7GV3pAA5bwKtuvPMKegh/7gowalZZUd93DRPSpdW,iv:pRObb9a+SkJI3ureUT1eQGb1rhy+DH4/109gUSj8lPI=,tag:TtRZFhcrzXfW9uD2/0IyFg==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSzFPeUFCSlhPbFZiSjB5
        eGlySytmV1lQbnJCdWwzVDFYUXJrYWhURVhRCjIyNVhLRDNjdE5IMitidmlPVjJN
        YVppREFqcE5xZEppaTUxZlNGSUZpZnMKLS0tIFcyejZFRjBDNDBlLzh1eHI4WFZL
        UVBuVUlWMC8zL1NGRHVuRm9sYWZEU2cKwq8+LTntjBbzF+qb0d4bEQevxfgaHbgD
        FfLgq9A+6H9yQFzAfL45q4QkqYMXYhCQ7uy6BOv/LKkkwtY6QpqbaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:55:48Z"
  mac: ENC[AES256_GCM,data:rYJrzF+3NVuO05h0L1mHeombmpjIi8XZfQXNledXNtybLGydq4QTDPpog15qpQCelkP3DlllpZpm/M5g6X2uCvNB2Phpd9ukI2CqUzq0MdIhedeMcGd8sR+RfNCOzpY4YSxRjAxLHYELfi7RAyh9fQu53FeNp+1Vpe4UTk/sqtw=,iv:oGorPVaxpB98R8OGg1e3oF3kRfdE51MFInXc6NbzOpQ=,tag:BvJqMK80Y+9/Cu3xEPkZRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
