apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aliKjwAAZEjU0B5zYsEthNhJmh6IOORC3ygtO4UnHIQ5yIAxGyUQfUz/HgkjftCCFg2yw4Dz399eEDqLXUnFU9/2RVTSgYTRYMVeKD2pPJLBsyYKFnE2rQx6axZvewm+ePojCJz775MzxtQsRMn5HfKrRFtqkmaIABiEmcV1d5A9UDi6iDAKJtcHm/Dn4A29Rz+Px8R9NCu5MNitc3TPYGRP8xkCAdhxyERshqoJE6G6B3Z+,iv:lD64Ri9JjkxEB7BbqkgN2usxnhd8Uurf2Te+dCR579c=,tag:D1+mWV+WmHpMcNMQAQZe4A==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWnhYcTVkRkxObWVQTGR0
        cE8zYXBCVXV0Z2U1SWFjOHpCSUV4SWowblRJCnpqV3ovb1lNOTJvcHRsaWxpclF4
        czVQaURTMFYrU3ZaL2FPNUZ3QkN4eEkKLS0tIDBPV3BTZ2J4WVRKUjZTNnhzRXBD
        cjhmQ1BPdkh0eDNvZGJIY05pbnJKNjAKAScmGwwN6DQ7LagFroAFXaGMO87yVNle
        aU/Ub34fcqDtkt6vyTqsheGmjVONTkKjmTajjtQ3VEpV2HcNiYOL9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:28:17Z"
  mac: ENC[AES256_GCM,data:+/rOqlMl0tsxA4T18gECcxmi50CqbCeu3jt/FCO2tRz3GiO/5BXTLtfBsJhWXlJm5LN5auQgHLMxWIaHkoYL4mGsBSIn6+9jyCNYM2Qyey3DuVeGd24p/qb7GrNFGiV6/ybWN6fszEsl6bM9bfDrNmTY4wwSgYIr6/fkSYcb274=,iv:NPHC64R0ECwk5YAdlFm9zN1n/xZ5rbfiiJSduX/b8a0=,tag:Y/DIqTrQpeCbz6/Zr/BESQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
