apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:M66LfD/2pJngfKe1hp872CcsFz5VEYXpDgTunxfdGm0z0zNVHXIsCl1as7D6mxYrtQeLTLCtOs+/jHi0l3DyMRqt45x8tu+TYF6J9//+6onr8sbR0y0Upgv4VoLwjOF0BQpsIP98erg9cCOei6KxgunKQOF0RgDvJqQwtfNqgbGcKQEu/+TDPdS0/topoF/j8K2aHhFsRFWDeVlat3gYz/uyuhtraXCh4Z8NShk3KZKPJXUe,iv:I5sFI+X2qQmp1IS/LibIV46zyFNxrM5mSf4p+dSU0r8=,tag:DE5Dg3SwcywF76Aq92LBTg==,type:str]
sops:
  age:
    - recipient: age1e0q6ugdp3pgka4tq7udj6f9rhxyhtrcvvauqj2mnxhtu3k60y4usraaqah
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVlJFeG40QTdFY1l1dmJH
        NGlmQTZacm0yaGZiVkZseG9jdEZTMmlvWUhjCkw5NEZOc1Q3ai9ZVmFZOW9qUEI1
        WmZpUDNiZWhFbnlnNGNCSit0ZytZaGsKLS0tIFRiK0ZUbktYdG1aVEdIZXdvYmlG
        cnFuNzI5c01Ia2dHYXN0SWMrTzRFWmcK6Jq5OLikUkfHQEzoNz9NKVR+Hl8e+Qh9
        PIpdJkoe2i144lJgUsPRAhz3YO7oxRY4VAffknIHhscCit2SpUv4Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:30:30Z"
  mac: ENC[AES256_GCM,data:6qdLw5XbwK+UDBzG9f+4wp6FMOTOQ8wBQOADZr56f0M/i/PiDiLI4a2y5g8DjMII12W35kyOdqkUh8/tMy84FBzvAuv4pfNn/maTUUyPqoIW7ZSSBPNrSjp3PQ7fAt37Qg06ofexNQ2njZ4AqUVfx2gAaDX6JWKAlGr2nsPLf5g=,iv:H0qbQt84MrrayB5L8zdCbAK+CimAscuZIJc4fL2+P0s=,tag:emEtmj06jxbrCRZ8B+vKnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
