---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudflare-tunnel-lan
spec:
  interval: 10m
  layerSelector:
#    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://docker.io/cloudflare/cloudflared
  ref:
    tag: latest
