apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3y1Wx0pleHZCbp45JGUVj/GFBVEAAp5uZ/RlEN0fhIIsh3A21z36NA==,iv:9hqqL9y9XLl1q4FDxHYVdH54Mc0CsyhkAqj9xr43HcE=,tag:ZfWn9r+izn9sAs4gxcHdJg==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGh3SmJXMmdEMUU4MjFi
        OXBPTHJtaXhSMzhpdnNZZVdsS2UvNnJVWmdFCnhkQTdqTTBaaGZmZVVGVXRUaGNM
        S1ZadHpMQ0NFbXVDenVuamNRQ3JhN1EKLS0tIE1HRjV3bUdZVDJ0REZ0RmFNbUxH
        Z1V3R1N0eUd1T0ZuVGx6cVlmTGtxVjQKaHwQRUFAwa8LefCSb8BUa5eelgrtnoA0
        a33SMRLSucAIO3pTptD9fb+PMsZ/AfkLTpNxFeGeuiRrUbwVUeYnUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:03:38Z"
  mac: ENC[AES256_GCM,data:uYUF3Dk7kYrET3kIIv0eCtLJFhRm/OEkEWKFxjhmqUDiEztosX0GpguRyHdFuSGWUkv1PBZzPJTGb6c/a/kla6DXHuuurdZ49ZfuSvoEsrp9tfuWYMcPdOZzERTS4keH+PFozKaSNqd3n+2HTzCRTYT2d9rcvbgSyMiNm9MY/ow=,iv:WpiLZqEUFcEHkfWSs/8dvAaxoWVj4vbTu8UHAVuWmcw=,tag:laxD97KnIeRfqhRwnR7Dkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
