apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:j8BuXswNEecEITgWMrf7QQv11RKjcMu86Je7jYDvDiWUImATQfj06A==,iv:dyXPJtf+MnnO6Jbdn592ShwIjRd3rj+JomVY31/N6Qo=,tag:uEavsIrVkkv2mDZERaA+Dw==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeVV1Sjc1MS9tYWZnSjhP
        bHRvdkJsR3NQNjJDNjVRdmd1dERxclpFa3pZCk1UNEd2dWc3UWVuNGh0dE0wRWJ5
        TytEZ1llVnhiQnNEVWF6VnJSL1NYMXMKLS0tIHVHeDBKZlZWUzFFeVFWdWNkSGh5
        NlQ1Szc4emtiZTNEMGJrdkpsbDI4bjQK3WZ7YIlp5eUeNf9pZ6kGRDxHonremL/+
        kzDbBE0RuvLtR6N+5cUHwbfVcW//lKkl6rvGrChH6ZDEsCMC/5VSBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:07:32Z"
  mac: ENC[AES256_GCM,data:JvKHwWE78JEaD/YEKftaVl3KXxNm+7RFR2icJk4R6Gqql50loDVZ9TpQQs4N/v721zrNd9YTJeGlAGeWzGEjZ2hdmRt3xSLH2jN3A/TRrmY5AydQf604AX9m6lWgbGypI5pO5AnIahTRhTHGh1LzcRwEtk6YtbnF314faJoeB8Q=,iv:xPvwdIfugtafOliS9FjctKZAaFV8EA19xqfaHiaH/EM=,tag:HDf4uqQn4sV5pF5ETMLS6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
