apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:l2M41A+gxTU+i8UIEI/J+8+h6LilHxjkABXaGCIJlBMR1dcW4RllGQ==,iv:bKX1cbqgZVrzxnX2pln6pSZ4MUQ+9iUaLTFAUoKKk6o=,tag:J0k/nf5Ffhce7MLVQLt5bw==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOVU1SkM2RHhJQ0wvVEtS
        NU9kQ3ZmNzdFOTNHaWdKZ1MrczhOeU9abndrClB3bkJqQ3lEa3NXemNyY1Vvcmxu
        TloybHVwb0JZdkw2dVB4STVwQTNTSGsKLS0tIHhRVEdEYmlGTTg0VC9ZM3BQckxE
        N3BVbElwTVovTC8xeXAyKzIzeVB0NHcKsuHaTCaaKI+0+gxS2L0oYhw4bIb5+S7H
        D+XOErVCCFaT04jvcUhSPoEBeAF3GZP2kkfmFKI5OQYOCzT4q9aKYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:12:56Z"
  mac: ENC[AES256_GCM,data:NdURLP3vVQCV5iZC3q+PUWTuGYnO1QEbNe0xxyGeFLTvzfhX/w0ZwYz9i7aIJ6+gfYNK8n6CAhtA8BMHx8lJcDhI4ZddvW5sxnVO59RpD4ixAT6AsJTOS+WEBQrsahNAAS+yeJHy9Tj6dsxqQP6RfhCEWZznYc+Tt0poqeZhXjI=,iv:DdtXRPbUH/LrfhwPWUGOiezCQibbZ7ZlYfcx/69r1q4=,tag:ZqMP6R6L0WJENw6olOA7Gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
