apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:a8zDMvKMQ9Nj3MVtlmVNX6BE9MAyCrzPgo+Ju47vTjPvKdkPfwTxzg==,iv:4i82p6htgnkNwBUhY/UQiQlg3VyYKEYRZxIKZn7QUf8=,tag:fmc9kf2xQc0UO/I5ZKOieg==,type:str]
sops:
  age:
    - recipient: age1e0q6ugdp3pgka4tq7udj6f9rhxyhtrcvvauqj2mnxhtu3k60y4usraaqah
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ek9idkR4N3RhTjE5aDNp
        OTZGQ2xoZG1lUVVnT3FPZGtLTEl3ekJwY0F3CjMxWEluSTBUSE1DY0pTaXF1Lzl2
        QmYrTUI1UHJsemVYMmhmRi9DN3R0aWsKLS0tIEhQcGNiNkw4S084ZytacWFoQjcw
        TkhOZjdUQnhnM0J0YWxEVm8vdmp4WkkK/3YClFEDfBjiYYYlTjQV8+xztxo5iSVS
        ffnGKdu56H32k+qZiDHI1cGx71xytTm8YP1mhdwiKDPSuY3jK4xJrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:30:30Z"
  mac: ENC[AES256_GCM,data:bcL1FebxYre+PANHKXhIy4J0IPf5Zej+Sv2mhwP+eMcsu4HWbWsLkLCV8iyp6C3clfXSCHVDD7baCTU94Sn2otXh/YhXD5Xl9hpFT0OJ6DV2FIZlq2kYRKIBy0G1c08lLUPT4NPTwqUoPMimWdb3kYmdl6TBg3ZwxXquW2802qA=,iv:47FRgE8IOLQWp3MdcGZDP7MokFIDOp2xY0Y0x7jtqfE=,tag:GKzG8K0aMN+hrNiL3eqn9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
