apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:mEzylJfIhXVRHKxFv0hKxVzE47opoUex15r230d0KqAtNUTJLdkpZA==,iv:IifmQ9+g5rqlQEGIAgVP8c+zfWfUWLOpSmD0Zy9JYvA=,tag:B8RLkwW6lx/UxlltlHG58w==,type:str]
sops:
  age:
    - recipient: age1earfmcl5v8tdsa852973v5mk27dpzay4jdmqj6wgtl0nc8mdnd4qa6t42x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIc3luMklqMVBnd1lCNS9L
        WXM3dGpubTVDSFgvVmFPdDZrQVZ3S3cwWmlZClBUYXNwdnBjemxqTkZ3NWRUbXBG
        NThEVlFnTm9Jbm9Sd0Z4WTVWMDQ0dzAKLS0tIG4weHp2eGQvdk5ROUJjbVhmRTF2
        b1c4NXBmUVJ5NUJNMmpJZkVhazNoMncKlgpxlKkJ5wUrcjkk2L3e85wUYUFITIPI
        WxgVGxuMJhBKR2nW/NUHjZvTvbLPjo4PL7sq3pqxSjCZqofofUd49Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:55:48Z"
  mac: ENC[AES256_GCM,data:JeGCJ3QA52UiUTO5R7BJOs2Iows4GyJMYZqqNB5ERjLHVZHkDGerUiHXdkYXsWLQnuJPqM/uaU82ieqfeiaDhcvJvWdCR7ijiRcuRLcPTMomzdfM0pdj4ET5S4iK3iv4Ym1r8Is1jHeubW3oD/f44eNHfNSOcyLM6/Zk4YXE1Wg=,iv:0waN4Pfi34rNGw3pW+xndJtIf07kYd56CF/7SLLBvn4=,tag:NjeV4OuyebHWmnHrT8HeQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
