apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BB1MJhqPMmt8ozPIxTknlII+eghLz1nlsTFTJIsnikfroUDtxQPFSQ==,iv:31hac1KXhCNZmtzXHXtviXlvtDQDLNNM68GJyvAAWO4=,tag:ksEQCIr2flkh/5q5+0TW7Q==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRy9nVk84K0lTYlBUdUFn
        ZGI4REVZVWlRT2dYZDJKTVJqY2dkRFRyQ1YwCjJ5aWJvciszSGtBUDZZMGtQVHZU
        alQvTVAxRUt3SkdMc1JlamhscFNKa2MKLS0tIE1ibmhEZ1R4WFYzdkpYakhZZFF1
        OHRMVGY3aWF5OU4zTzB2cGtFL2JmUjgKIGSMa0aH5uCoP/k3bzCY48Bc5cLH4Bq9
        4zowmRgPgI5iLsRqNCRQYxo5VUu7f01jLjUovT8EL7fpO0T5ohiuXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T06:28:17Z"
  mac: ENC[AES256_GCM,data:gqip5UfLYwz0P4HPW+ndVUr/oQYNluN0aR0OvsIRLmjlngmCmqv3CDzOGL1klLjFP0hGf6/EI01f+/HG3UnuKwSBnItLoWC5ycR49TYvEiit6xrPcozJdiZH5A/eHf0QORSuyOmHzpli1tJX/duYrsEMHRFBebG01/Je/KYUeD8=,iv:3vMktGeLe9hIrPbWFp/H/9L2V3s8RNdhbRN9MECxIXE=,tag:hK1VSsIQRQs8UfxnJNm2MA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
