apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:RpkT9/qsL/5x6cl+sJzjGbL8NPfIvNmuDLX++Ts/+p5ih6G4d80Efg==,iv:MgEmD+uizHu5uNNw8wvJes/FUXAxR5MIlJ0M7sfKcFk=,tag:mxPOMod3/Bpd28phXp/BTA==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZREJZVFFqUFYrTE50N0Ft
        S3NESm43MTc4cHhES1IzSVIwZWZmeXBRMFYwCjJBbUtYekJ1RDUzK3ZZcU1SS1RE
        OW43YWJaZTlPNnJFMnpYZTlFbjFiSUUKLS0tIDJLYXpEUisvMGc1U0puK0Vndng1
        QlcvVjRpNlUvMDIvTTE1ckYzOUNsdDQKafBCbYmlNxnOS8F00QE+mZb4tg6lbpq1
        moFt6ba4K0C3RRoktNtfeSB9kFJTySmlmpK+VNa2CbUwxSaHV/u5mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:41:07Z"
  mac: ENC[AES256_GCM,data:oWoKTMjkrA6weFXz0B2KM6u+uDLto0cQSEhbHqx4D9b6s0TkcxUvI9vLBqfh1jamj5sQTa8SlS8JYDw6h5947494/2mhWj/PtPIiF0ldp0jx3d7+LN+jtQ4LvvTvMHOL/r232MWoAN6AruVWBrTOySOFDCsONpvPsJd3jwJ9bEk=,iv:E0+pxHd33EHWwawiAV3aOOMfWzfHHzk3sjY2dFo+uoo=,tag:BxdNmwD4vgopWETxuOQy+w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
