apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:tCzQWKKM8D22f5bajITBU9uYSaV5ZjCDCrQXgqXYJP9VKY1+3GwOKQ==,iv:qIPemLGxtA03yX5KwXvz28kPCtEBhr5OIVJ8fQqkPNs=,tag:r9SxFw3xokVVKhcn+LzLSA==,type:str]
sops:
  age:
    - recipient: age15u38xwergelq3yt58cqe6aytdkhywda8993y53tewadsxeegcc3skuk6cg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVEJwV1hGbXE2SDVic09P
        L2tlVmFDdmkvMnBTM3lPTFdFdGlXK0tnRDNVCkhlVGNNV0NTN29jczRUQkhjVGJZ
        QjdTTHMweXhRV212T2xicTVOUER4RjgKLS0tIEIrTXBRbUxZajAyeC9BbytMVzdG
        dHh2RlBiVllYU0pNd2txNXpkSDlMdE0KtWrkVmsI8AZKn534gh/rubaiuDre91uY
        kMSajO7t0JONecy7s+TnSuV50kO/z9vlWc74nA3FwcxteXx+QNgwMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T17:59:27Z"
  mac: ENC[AES256_GCM,data:z8kGov/tV2NrZ5FJfMK/qXbb6aq+NMUjgjO73bIQwg0WciGy9r0/uWqUbdWXAXmAofEJbNNJisj2WScBP66k6LcTzj14d4qzdIH56+XPjtkA/ndaptwBQF4/9fBPA1fyE0nN1dp5GwWLYIu8w/29Y5Le3P6ignKkuAHGPg712dg=,iv:vH8Obz7LG1FtMubMz8Oa7A3yKSa7JFrmI/uvv2/JgK4=,tag:2QZJldzs/MAsZcA+CkR2aA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
