apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PvmevARVpy51mKf33AhnrFf+kSvO07IFl+RMGTKuRDoWVMpF17T5lQ==,iv:4h99e7tZaThxxfk+tdB0123WmMaNfvsJ4He2Hx0cFlA=,tag:6vmmnXoBbGkCzKa6Sz0vig==,type:str]
sops:
  age:
    - recipient: age10vcm39njm2lc3wr9u50yvxqshq5hwyg4rj40nexyup3srydjhcjsx9hpyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnAzTWJSZnJqUDN3MHZN
        aFo5ZFpQYTJ4elBlazFpQ2tnMGdhb3JJTjF3CjBQcUxxUkdQS091NHR1dHpSWnEr
        cTU2TjJKMjFPWHYvUTBRZTJWOTIyc0EKLS0tIE42cW03eGFLbVZmKzRmZURrdFYz
        NktsOStZY2VqRFFlOHdJbDVvVWlBMjgKiqMLQ5O3I4aawP4EsXoW1eK8tP6HnXSk
        D9NYHErzTkSIWo3xKBKmzyDCIvo6FCbvO5dKDzLRFpO/OJYeVUvPLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T05:12:27Z"
  mac: ENC[AES256_GCM,data:qQcrv0X0t03J++JNWCyb3R3zQQP2teh4WAvsxFDfKRsEkkCdeGNHTxo9jW3OvPwSQ7fDxlO9dBaHFRGp2Evr2Xui/Z90FgAonz5n6VjVhyAtGr8gfZNKWo7JMy8d1skONwGKwwlU/A7aA9dlnly9zcRx//Dg1R3BbAalQWIAQCc=,iv:vBsoNc+J4WlkZeivphnd0B5EZTE6HtLHayJ3JU05Nuk=,tag:SoZNEmU6iyjs/Vd0sEXjYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
