apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:oD/D8V/x7tsu/b3RZp8su2Rj+3V/mYCZXq71Cd5WznJwrZfI2f2d1A==,iv:AXiXIrmnVUXpbrn/9MkMQ9z2iCUUgkEwxzmWak4mKkM=,tag:yWOqKj3StNUqktkWq1jimA==,type:str]
sops:
  age:
    - recipient: age18wgrx33au72vgf5864ergvs6djplyepnm9zvan83tf52ykrqc53scp2dn5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR003SE9KUDBHMElqYW1G
        MlRISFdGaTFsb3czL2lBRzZUQ1Z0Sm9SSDBVCmNSc2xJTDFhNExCL3lpVDJwNmZt
        RmFDS1I3dnBrY29wTlJsVzFkY2RYYW8KLS0tIGF2TlFLSFJTMUg5aGJ4S1AyVGlj
        UkhCQk1HbGl0SDVYV3lSYnQ5YWRURjAKctuv54NpIhfUB4ts5S4Y8ooB/t2fRbEF
        fchWmpgf/bo4E6srrA/vJBaleV5qDC3YwbCf1IRqKeLYfEQRRyZFfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T11:52:28Z"
  mac: ENC[AES256_GCM,data:dfGUlMzlftRrJtjS9R+Cx+YnajfMtkTdL0zytV5ZNrhOd/1osQIAi9EkMfBHLNdrOIyeq4yitQK/l1VRO0WQNEFFnK0O/AtJV6z5VXksdjwb23WjeansyMg8I5y7FPvuuCgVq0kQ9nt1GvjNWUlDtJJT0QoqiNsX5xcPeyyZHoM=,iv:usGTemArSewTAK6J0CdfKbsCVlJbCY9EpsldevExDUo=,tag:W4xtgQccZPFSyi7xwjONTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
