---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mariadb
  template:
    metadata:
      labels:
        app: my-mariadb
    spec:
      securityContext:
        runAsUser: 0 # Explicitly sets the user ID to root (0)
        runAsGroup: 0 # Explicitly sets the group ID to root (0)
        runAsNonRoot: false # Disables the non-root user enforcement
#      hostNetwork: true
      containers:
        - image: tiredofit/mariadb:10.5
          name: freepbx-db
          env:
            # Defines an environment variable
            - name: TZ
              value: "Asia/Taipei"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "asterisk"
            - name: MYSQL_USER
              value: "asterisk"
            - name: MYSQL_PASSWORD
              value: "asteriskpass"
          volumeMounts:
            - name: db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: mariadb-nfs

---
apiVersion: v1
kind: Service
metadata:
  name: my-mariadb
  namespace: default
  labels:
    service: my-mariadb
spec:
  ports:
    - name: db-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: my-mariadb
