---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-mariadb
  namespace: default
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: mariadb
#      version: '24.0.2'
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde
        namespace: default
      interval: 5m
  values:
    replicaCount: 1
    env:
      TZ: "Asia/Taipei"
#    hostNetwork: true
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: "mariadb-nfs"
        subPath: "data"
        size: 50Gi

#    persistence:
#      enabled: true
#      size: 50Gi
#      existingClaim: "mariadb-nfs"

