---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: krakazyabra
  namespace: default
spec:
  interval: 5h
  url: https://krakazyabra.github.io/microservices
#  url: https://charts.bitnami.com/bitnami
