---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: groundhog2k
  namespace: default
spec:
  interval: 5h
  url: https://groundhog2k.github.io/helm-charts/
#  url: https://nicholaswilde.github.io/helm-charts/
#  url: https://charts.bitnami.com/bitnami
