---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-mariadb
  namespace: default
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: mariadb
#      version: '24.0.2'
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: default
      interval: 4m
  values:
#    replicaCount: 1
    env:
      - name: MARIADB_ROOT_PASSWORD
        value: "rootpass"
      - name: TZ
        value: "Asia/Taipei"
      - name: MARIADB_USER
        value: "asterisk"
      - name: MARIADB_PASSWORD
        value: "asteriskpass"
      - name: MARIADB_DATABASE
        value: "asterisk"
    storage:
      data:
        size: 20Gi
        existingClaim: "mariadb-nfs"
