---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-mariadb
  namespace: default
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: mariadb
#      version: '24.0.2'
      sourceRef:
        kind: HelmRepository
        name: groundhog2k
        namespace: default
      interval: 4m
  values:
#    replicaCount: 1
    env:
      TZ: "Asia/Taipei"
    storage:
      data:
        size: 20Gi
        existingClaim: "mariadb-nfs"

#    hostNetwork: true
#    persistence:
#      config:
#        enabled: true
#        type: pvc
#        existingClaim: "mariadb-nfs"

#    persistence:
#      enabled: true
#      size: 50Gi
#      existingClaim: "mariadb-nfs"

