---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mariadb
spec:
  parentRefs:
    - name: tcp-gateway
      namespace: default
      sectionName: mariadb-tcp
  rules:
    - backendRefs:
        - name: my-mariadb
          namespace: default
          port: 3306
