#---
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: HelmRepository
#metadata:
#  name: k8s-at-home-library
#  namespace: default
#spec:
#  interval: 15m
#  url: https://library-charts.k8s-at-home.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-at-home
  namespace: default
spec:
  interval: 15m
  url: https://k8s-at-home.com/charts/
