---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homebridge-nfs
  annotations:
    nfs.io/storage-path: "k8shomebridge" # not required, depending on whether this annotation was shown in the storage class description
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ds2-homedirect
  resources:
    requests:
      storage: 10Gi
