---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "10.9.1.2"
  listeners:
  - name: mqtt-tcp
    protocol: TCP
    port: 1883
    allowedRoutes:
      kinds:
      - kind: TCPRoute
