---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: TCPRoute
metadata:
  name: mqtt
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: tcp
  rules:
    - backendRefs:
        - name: mqtt
          namespace: default
          port: 1883
